"""initial schema

Revision ID: 9e50ad514d2d
Revises: 
Create Date: 2026-09-05 15:55:44.390680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e50ad514d2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('GAS_CONCENTRATION', 'VENTILATION', 'PAST_VIOLATIONS', 'OVERDUE_ACTIONS', 'EQUIPMENT_HEALTH', name='compliance_category'), nullable=False),
    sa.Column('sector_id', sa.String(), nullable=True),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_scores'))
    )
    op.create_table('sensors',
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('sector_id', sa.String(), nullable=False),
    sa.Column('last_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_risk_score', sa.Integer(), nullable=False),
    sa.Column('last_risk_level', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id', name=op.f('pk_sensors'))
    )
    op.create_index(op.f('ix_sensors_sector_id'), 'sensors', ['sector_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('mine_manager', 'field_worker', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('incidents',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('sector_id', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'ASSIGNED', 'RESOLVED', 'ESCALATED', 'SIGNED_OFF', name='incident_status'), nullable=False),
    sa.Column('assigned_worker_id', sa.UUID(), nullable=True),
    sa.Column('field_remarks', sa.Text(), nullable=True),
    sa.Column('resolution_photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.id'], name=op.f('fk_incidents_assigned_worker_id_users')),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], name=op.f('fk_incidents_sensor_id_sensors')),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk_incidents'))
    )
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', name='inspection_status'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_table('telemetry_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('sector_id', sa.String(), nullable=False),
    sa.Column('ch4_pct', sa.Float(), nullable=False),
    sa.Column('co_ppm', sa.Float(), nullable=False),
    sa.Column('dust_pm10', sa.Float(), nullable=False),
    sa.Column('displacement_mm', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], name=op.f('fk_telemetry_readings_sensor_id_sensors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_readings'))
    )
    op.create_index('ix_telemetry_readings_sector_recorded', 'telemetry_readings', ['sector_id', 'recorded_at'], unique=False)
    op.create_index('ix_telemetry_readings_sensor_recorded', 'telemetry_readings', ['sensor_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_readings_sensor_recorded', table_name='telemetry_readings')
    op.drop_index('ix_telemetry_readings_sector_recorded', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_table('inspections')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensors_sector_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_table('compliance_scores')
    # ### end Alembic commands ###
